# Project: OOP_project
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = BaseRestaurant.o Rest_Taichung.o Rest_Tainan.o Rest_Taipei.o main.o
LINKOBJ  = BaseRestaurant.o Rest_Taichung.o Rest_Tainan.o Rest_Taipei.o main.o
LIBS     = -L"C:/Users/User/Desktop/DevCppPortable/MinGW64/lib" -L"C:/Users/User/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/User/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/User/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/User/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/User/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/User/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/User/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/User/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = OOP_project.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

BaseRestaurant.o: BaseRestaurant.cpp
	$(CPP) -c BaseRestaurant.cpp -o BaseRestaurant.o $(CXXFLAGS)

Rest_Taichung.o: Rest_Taichung.cpp
	$(CPP) -c Rest_Taichung.cpp -o Rest_Taichung.o $(CXXFLAGS)

Rest_Tainan.o: Rest_Tainan.cpp
	$(CPP) -c Rest_Tainan.cpp -o Rest_Tainan.o $(CXXFLAGS)

Rest_Taipei.o: Rest_Taipei.cpp
	$(CPP) -c Rest_Taipei.cpp -o Rest_Taipei.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
